<center><h1>Ant Colony Optimization

## Formulation

$$\large P_{xy}^k = \frac{[\tau_{xy}(t)]^\alpha \cdot [\eta_{xy}(t)]^\beta}{\sum_{k=1}^{m}[\tau_{xy}(t)]^\alpha \cdot [\eta_{xy}(t)]^\beta}$$
    

- $P_{xy}^k$: Probability of the ant $k$ leaving position $x$ to choose $y$ as its next destiny
- $t$: Iteration
- $\alpha$: Distance influence
- $\beta$: Pheromone influence
- $\tau_{xy}(t)$: Inverse of the distance between $x$ and $y$
- $\eta_{xy}(t)$: The ammount of pheromone present in the route $xy$
- $\sum_{k=1}^{m}[\tau_{xy}(t)]^\alpha \cdot [\eta_{xy}(t)]^\beta$: The sum of contributions from each ant to the pheromone in route $xy$

----

$$\large \Delta\tau_{xy}^k = \frac{Q}{d_k}$$

- $\Delta\tau_{xy}^k$: Pheromone laid up by the ant $k$ in the route $xy$
- $Q$: Pheromone atualization constant
- $d_k$: Total distance covered by the ant $k$

----

$$\large \tau_{xy}^k(t) = (1-\sigma)\cdot \tau_{xy}^k(t-1) + \sum_{k=1}^{m}\Delta\tau_{xy}^k$$

- $\tau_{xy}^k(t)$: Updated pheromone for the ant $k$ in the route $xy$
- $\sigma$: Pheromone's evaporation rate
- $\tau_{xy}^k(t-1)$: Total pheromone in the route $xy$ in the previous interation
- $\Delta\tau_{xy}^k$: Sum of the pheromone of all $k$ ants that were laid up in the route $xy$

----

## Example

Let's take the Traveling Salesman example:

<img src="TravelingSalesman.png" alt="Traveling Salesman" style="width:100%">

In order to simplify lets assume the 5 cities:

- A = 0
- B = 1
- C = 2
- D = 3
- E = 4

In [1]:
# List of distances between pairs of cities
alpha = 1
beta = 1
sigma = 0.01
tau_ini = 0.1
Q = 10

dist_list = [('A', 'B', 22), ('A', 'C', 50), ('A', 'D', 48), ('A', 'E', 29),
             ('B', 'A', 22), ('B', 'C', 30), ('B', 'D', 34), ('B', 'E', 32),
             ('C', 'A', 50), ('C', 'B', 30), ('C', 'D', 22), ('C', 'E', 23),
             ('D', 'A', 48), ('D', 'B', 34), ('D', 'C', 22), ('D', 'E', 35),
             ('E', 'A', 29), ('E', 'B', 32), ('E', 'C', 23), ('E', 'D', 35)]

In [2]:
import pandas as pd

def calc_prob(row):
    return row.tau_eta/sum(df.loc[df['orig'] == row.orig].tau_eta)

In [3]:
df = pd.DataFrame(dist_list, columns=['orig','dest','dist'])

In [4]:
df['tau'] = 1/df['dist']
df['eta'] = 0.1
df['tau_eta'] = df['tau'] * df['eta']
df['p_k'] = df.apply(calc_prob, axis=1)

In [5]:
df.round(3)

   orig dest  dist    tau  eta  tau_eta    p_k
0     A    B    22  0.045  0.1    0.005  0.376
1     A    C    50  0.020  0.1    0.002  0.166
2     A    D    48  0.021  0.1    0.002  0.173
3     A    E    29  0.034  0.1    0.003  0.286
4     B    A    22  0.045  0.1    0.005  0.326
5     B    C    30  0.033  0.1    0.003  0.239
6     B    D    34  0.029  0.1    0.003  0.211
7     B    E    32  0.031  0.1    0.003  0.224
8     C    A    50  0.020  0.1    0.002  0.141
9     C    B    30  0.033  0.1    0.003  0.234
10    C    D    22  0.045  0.1    0.005  0.320
11    C    E    23  0.043  0.1    0.004  0.306
12    D    A    48  0.021  0.1    0.002  0.168
13    D    B    34  0.029  0.1    0.003  0.237
14    D    C    22  0.045  0.1    0.005  0.366
15    D    E    35  0.029  0.1    0.003  0.230
16    E    A    29  0.034  0.1    0.003  0.250
17    E    B    32  0.031  0.1    0.003  0.227
18    E    C    23  0.043  0.1    0.004  0.316
19    E    D    35  0.029  0.1    0.003  0.207